export const GET_CURRENCIES = 'GET_CURRENCIES';
export const GET_CURRENCIES_FAIL = 'GET_CURRENCIES_FAIL';

export const GET_MARKETS = 'GET_MARKETS';
export const GET_MARKETS_FAIL = 'GET_MARKETS_FAIL';